name: UI tests  # Название workflow, отображается в интерфейсе GitHub Actions

permissions:
  contents: write  # Для записи в репозиторий (например, ветку gh-pages)
  pages: write    # Для работы с GitHub Pages
  id-token: write # Для аутентификации действий

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load BROWSER_NAME
        id: load-browser-name
        run: |
          if [ -f .ci_env ]; then
            source .ci_env
            echo "browser_name=$BROWSER_NAME" >> $GITHUB_OUTPUT
          else
            echo "browser_name=[\"chromium\"]" >> $GITHUB_OUTPUT
          fi

      - name: Debug BROWSER_NAME
        run: echo "BROWSER_NAME=${{ steps.load-browser-name.outputs.browser_name }}"

    strategy:
      matrix:
        browser: ${{ fromJson(steps.load-browser-name.outputs.browser_name) }}  # Используем output из шага

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          if [ -f .ci_env ]; then
            cat .ci_env >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run UI tests with pytest and generate Allure results
        env:
          BROWSER_NAME: ${{ matrix.browser }}
          URL: ${{ env.URL }}
          WINDOW_SIZE: ${{ env.WINDOW_SIZE }}
          SLOW: ${{ env.SLOW }}
          TIMEOUT: ${{ env.TIMEOUT }}
          REMOTE_BROWSER: ${{ env.REMOTE_BROWSER }}
        run: |
          pytest -m regression --alluredir=allure-results-${{ matrix.browser }} --numprocesses 2

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results-${{ matrix.browser }}

  publish-report:
    needs: [run-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          path: allure-results
        continue-on-error: true

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_history: true
          keep_history_days: 30

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history